#!/bin/bash

cd ~/java/autojar

if (( $# > 1 )); then
    echo "$1 => $2"
    java -jar $1 -avc classes/production/autojar:lib/bcel.jar:lib/log4j.jar:src/log4j -p log4j -o $2 \
        -m autojar.mf -- "@classlist" log4j.properties
else
    java -cp classes/production/autojar:lib/bcel.jar:lib/log4j.jar:log4j de.monoped.autojar.Autojar \
        -avc classes/production/autojar:lib/bcel.jar:lib/log4j.jar:log4j -p log4j -o ${1-autojarneu.jar} \
        -m autojar.mf -- "@classlist" log4j.properties
fi
